spring: 
  profiles: 
  active: 
  - test 
---
spring:
  profiles: dev
  application:
    name:  springcloud-config-dev1
---
spring:
  profiles: test
  application:
    name:  springcloud-config-test1
 

