server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangweidongIT/springcloud_config.git #GitHub上面的git仓库名字
 

