spring: 
  profiles: 
  active: 
  - test 
---
spring:
  profiles: dev
  application:
    name:  springcloud-config-dev
server:  
  port: 3355
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: provider-dev
    prefer-ip-address: true
---
spring:
  profiles: test
  application:
    name:  springcloud-config-test
server:  
  port: 3366
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7002.com:7002/eureka
  instance: 
    instance-id: provider-test
    prefer-ip-address: true

