spring: 
  profiles: 
  active: 
  - test 
---
spring:
  profiles: dev
  application:
    name:  springcloud-config-dev
server:  
  prot: 3355
---
spring:
  profiles: test
  application:
    name:  springcloud-config-test
server:  
  prot: 3366

