spring: 
  profiles: 
  active: 
  - test 
---
spring:
  profiles: dev
  application:
    name:  springcloud-config-dev22
---
spring:
  profiles: test
  application:
    name:  springcloud-config-test22
 

