spring: 
  profiles: 
  active: 
  - test 
---
spring:
  prifiles: dev
  application:
    name:  springcloud-config-dev
 ---
spring:
  prifiles: test
  application:
    name:  springcloud-config-test
 

